# Flutter/Dart Static Analysis Configuration
# Enterprise-grade linting rules for 90%+ coverage and 95%+ pass rate
# Modified 2026-01-28: Simplified configuration, fixed YAML format

include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Treat these as errors (will fail CI)
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
    unnecessary_null_comparison: warning
    deprecated_member_use: warning
    dead_code: info
    todo: ignore
    # Downgrade cosmetic rules
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/api/generated/**"
    - "test/**"
    - "test/_deprecated/**"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # === Disabled rules (cosmetic/noisy/incompatible) ===
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_put_control_body_on_new_line: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    directives_ordering: false
    prefer_expression_function_bodies: false
    require_trailing_commas: false
    always_use_package_imports: false
    cascade_invocations: false
    unnecessary_final: false  # Incompatible with prefer_final_locals
    avoid_catches_without_on_clauses: false  # Too strict
    one_member_abstracts: false  # Valid design pattern
    avoid_positional_boolean_parameters: false  # Common in Flutter

    # === Enabled rules (default from flutter_lints + extras) ===
    avoid_dynamic_calls: false  # Disabled - requires extensive JSON parsing refactoring
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    unawaited_futures: true
    prefer_single_quotes: true
